### PR TITLE
Provide fully specified initial conditions

### PR DESCRIPTION
**Pull request by lochel**
I think all examples of this library should have fully specified initial conditions. Otherwise the behaviour is not well defined.
This pull request will only provide initial conditions for WasteWater.ASM1.Examples.SmallPlant.

### CODE REVIEW

**Comment by lochel** [comment]
I closed this pull request temporary since OpenModelica doesn’t like the changes and I wanted to figure out why. Now, I’ve isolated the issue and created an OpenModelica ticket for it ([#3536](https://trac.openmodelica.org/OpenModelica/ticket/3536)).
Anyway, the library should provide fully specified initial conditions. One with a better understanding of this library should review my changes. There is probably a better way of defining the initial conditions.

**Comment by dietmarw** [comment]
@lochel Could you explain in what way `fixed=true` helps here without having a `start` attribute defined?

**Comment by lochel** [comment]
First I added explicit zero start values to the model, which is probably quite bad since it isn’t a valid solution. So maybe there should be added suitable start values – I don’t know. 
There is an override file in `WasteWater/Resources/ASM1/` to provide suitable start values and that works just fine if the correct variables have `fixed=true`. When the fixed attribute is not part of the model, then different tools may select different initial conditions which makes the model incomparable.

**Comment by dietmarw** [comment]
Ok I see. I didn't know about those. I'm going to handle this the pragmatic way and accept the PR. I'll have to say that I purely do this as a "manager" that does not use the library but due to lack of active maintainers of this lib I guess it's the best we can do currently.

**Pull request merged**
